#!/bin/sh

## This script is intended to be used in conjuction with exuberant-ctags:
## http://ctags.sourceforge.net/

find . -iname "*.c*" -o -iname "*.h" > files

/usr/local/bin/ctags -L files -f tags --verbose=yes
