/* This is the file for alarms generated by lids */

#ifndef __LIDSALARM__
#define __LIDSALARM__

/*
 * Ideally, this would be way more configurable in the future, so you could
 * specify a log file, email people when a certain severity is reached, etc
 */

/* more to be filled in later */
#define CRITICAL    0
#define WARNING     1
#define INFORMATION 4
#define EXTRA       7

class LIDSAlarm {
      public:
            LIDSAlarm();
            ~LIDSAlarm();
            void throw_alarm(int urgency, char* message);

      private:

};

#endif
